# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PictureSelector/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImageLabeler(object):
    def setupUi(self, ImageLabeler):
        ImageLabeler.setObjectName(_fromUtf8("ImageLabeler"))
        ImageLabeler.resize(1000, 700)
        self.centralWidget = QtGui.QWidget(ImageLabeler)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.nextImageButton = QtGui.QPushButton(self.centralWidget)
        self.nextImageButton.setGeometry(QtCore.QRect(870, 510, 113, 32))
        self.nextImageButton.setObjectName(_fromUtf8("nextImageButton"))
        self.prevImageButton = QtGui.QPushButton(self.centralWidget)
        self.prevImageButton.setGeometry(QtCore.QRect(370, 510, 113, 32))
        self.prevImageButton.setObjectName(_fromUtf8("prevImageButton"))
        self.imageList = QtGui.QListWidget(self.centralWidget)
        self.imageList.setGeometry(QtCore.QRect(20, 60, 321, 381))
        self.imageList.setDragEnabled(False)
        self.imageList.setViewMode(QtGui.QListView.IconMode)
        self.imageList.setObjectName(_fromUtf8("imageList"))
        self.mplWidget = QtGui.QWidget(self.centralWidget)
        self.mplWidget.setGeometry(QtCore.QRect(380, 40, 581, 461))
        self.mplWidget.setObjectName(_fromUtf8("mplWidget"))
        self.mplvl = QtGui.QVBoxLayout(self.mplWidget)
        self.mplvl.setMargin(11)
        self.mplvl.setSpacing(6)
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.clickOptionsBox = QtGui.QGroupBox(self.centralWidget)
        self.clickOptionsBox.setGeometry(QtCore.QRect(494, 490, 371, 63))
        self.clickOptionsBox.setAlignment(QtCore.Qt.AlignCenter)
        self.clickOptionsBox.setFlat(False)
        self.clickOptionsBox.setCheckable(False)
        self.clickOptionsBox.setObjectName(_fromUtf8("clickOptionsBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.clickOptionsBox)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.eyesRadioButton = QtGui.QRadioButton(self.clickOptionsBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.eyesRadioButton.setFont(font)
        self.eyesRadioButton.setStyleSheet(_fromUtf8("color: blue;"))
        self.eyesRadioButton.setObjectName(_fromUtf8("eyesRadioButton"))
        self.horizontalLayout.addWidget(self.eyesRadioButton)
        self.noseRadioButton = QtGui.QRadioButton(self.clickOptionsBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.noseRadioButton.setFont(font)
        self.noseRadioButton.setStyleSheet(_fromUtf8("color:red;"))
        self.noseRadioButton.setObjectName(_fromUtf8("noseRadioButton"))
        self.horizontalLayout.addWidget(self.noseRadioButton)
        self.shapeRadioButton = QtGui.QRadioButton(self.clickOptionsBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.shapeRadioButton.setFont(font)
        self.shapeRadioButton.setStyleSheet(_fromUtf8("color:green;"))
        self.shapeRadioButton.setObjectName(_fromUtf8("shapeRadioButton"))
        self.horizontalLayout.addWidget(self.shapeRadioButton)
        self.eyesRadioButton.raise_()
        self.noseRadioButton.raise_()
        self.shapeRadioButton.raise_()
        self.shapeRadioButton.raise_()
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Diwan Kufi"))
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(510, 10, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Diwan Kufi"))
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        ImageLabeler.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(ImageLabeler)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        ImageLabeler.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(ImageLabeler)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        ImageLabeler.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(ImageLabeler)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        ImageLabeler.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(ImageLabeler)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpenDirectory = QtGui.QAction(ImageLabeler)
        self.actionOpenDirectory.setObjectName(_fromUtf8("actionOpenDirectory"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpenDirectory)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ImageLabeler)
        QtCore.QMetaObject.connectSlotsByName(ImageLabeler)

    def retranslateUi(self, ImageLabeler):
        ImageLabeler.setWindowTitle(_translate("ImageLabeler", "Image Labeler", None))
        self.nextImageButton.setText(_translate("ImageLabeler", "Next", None))
        self.prevImageButton.setText(_translate("ImageLabeler", "Prev", None))
        self.clickOptionsBox.setTitle(_translate("ImageLabeler", "Click Options", None))
        self.eyesRadioButton.setText(_translate("ImageLabeler", "Eyes", None))
        self.noseRadioButton.setText(_translate("ImageLabeler", "Nose", None))
        self.shapeRadioButton.setText(_translate("ImageLabeler", "Shape Tip", None))
        self.label.setText(_translate("ImageLabeler", "Opened Files", None))
        self.label_2.setText(_translate("ImageLabeler", "Image View", None))
        self.menuFile.setTitle(_translate("ImageLabeler", "File", None))
        self.actionOpen.setText(_translate("ImageLabeler", "Open File", None))
        self.actionOpen.setShortcut(_translate("ImageLabeler", "Ctrl+O", None))
        self.actionOpenDirectory.setText(_translate("ImageLabeler", "Open Directory", None))
        self.actionOpenDirectory.setShortcut(_translate("ImageLabeler", "Ctrl+Shift+O", None))

